### PR TITLE
Add Button Component.

### PR DESCRIPTION
**Pull request by manojkumar8400**
Add button component.
1. Primary button
2. Link button
3. Disable, enable button
4. Icon button
5. Floating button

### CODE REVIEW

**Review by Varu98 — APPROVED** [review]
Great!

**Comment by manojkumar8400** [comment]
> Great!

Thanx Varu.

**Comment by bipin7yadav** [comment]
looks great you can merge it

**Comment by manojkumar8400** [comment]
> looks great you can merge it

Thankyou Bipin.

**Review by bipin7yadav — APPROVED** [review]

**Pull request merged**
