### PR TITLE
Added Text/Snack-bar Component.

### PR DESCRIPTION
**Pull request by manojkumar8400**
Added some types of Toast in this component.

### CODE REVIEW

**Comment by manojkumar8400** [comment]
Screenshot from 2022-04-03 23-34-31

**Review by Chakravarthi0 — APPROVED** [review]
one correction, there is a typo in component naming, it is "modal", not "model".
everything else looks good

**Comment by manojkumar8400** [comment]
> one correction, there is a typo in component naming, it is "modal", not "model". everything else looks good

thanks for correcting me I will make this change on the next PR.

**Review by gopalbbharadva — APPROVED** [review]
Suggestion: You can add colors for toasts, like green for success, red for failure etc... ,

**Comment by manojkumar8400** [comment]
> Suggestion: You can add colors for toasts, like green for success, red for failure etc... ,

Thanks for suggestion, I will do it.

**Pull request merged**
